# Generated by Django 5.1.6 on 2025-04-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_data', '0003_premium_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium_member',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
