# Generated by Django 5.1.6 on 2025-03-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bmr',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='calories',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10),
        ),
    ]
