# Generated by Django 5.1.6 on 2025-04-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Sedentary (No exercise)'), ('light', 'Light (1-3 days/week)'), ('moderate', 'Moderate (3-5 days/week)'), ('active', 'Active (6-7 days/week)'), ('very_active', 'Very Active (Athlete)')], default='moderate', max_length=100),
        ),
    ]
